curso <- "Probabilidad y Estadistica Computacional"
semana <- 3
print(curso)
print(semana)

set.seed(2026)
dado <- sample(1:6, size= 240, replace = TRUE)
tabladado <- table(dado)
propdado <- prop.table(tabladado)
print(tabladado)
print(round(propdado, 3))

set.seed(2026)
dado <- sample(1:6, size= 2000, replace = TRUE)
eventoA <- (dado == 2) | (dado == 4) | (dado == 6)
eventoB <- dado > 3
frA <- mean(eventoA)
frB <- mean(eventoB)
frcomplementoA <- mean(!eventoA)
frUnion <- mean(eventoA | eventoB)
frInterseccion <- mean(eventoA | eventoB)
print(frA)
print(frB)
print(frcomplementoA)
print(frUnion)
print(frInterseccion)


set.seed(310)
sumas <- replicate(600, sum(sample(1:6, size = 2, replace = TRUE)))
tablaSumas <- table(sumas)
propSumas <- prop.table(tablaSumas)
eventoC <- sumas >= 9
eventoD <- (sumas / 2) == floor(sumas / 2)
frC <- mean(eventoC)
frD <- mean(eventoD)
frUnionCD <- mean(eventoC | eventoD)
frInterCD <- mean(eventoC & eventoD)
print(tablaSumas)
print(round(propSumas, 3))
print(frC)
print(frD)
print(frUnionCD)
print(frInterCD)

set.seed(811)
tipos <- c("Correcta", "Lenta", "Falla")
probs <- c(0.75, 0.20, 0.05)
estado <- sample(tipos, size = 400, replace = TRUE, prob = probs)
tablaEstado <- table(estado)
propEstado <- prop.table(tablaEstado)
eventoNoCorrecta <- (estado == "Lenta") | (estado == "Falla")
frNoCorrecta <- mean(eventoNoCorrecta)
print(tablaEstado)
print(round(propEstado, 3))
print(frNoCorrecta)

set.seed(811)
tipos <- c("Correcta", "Lenta", "Falla")
probs <- c(0.75, 0.20, 0.05)
estado2000 <- sample(tipos, size = 2000, replace = TRUE, prob = probs)
tabla2000 <- table(estado2000)
prop2000 <- prop.table(tabla2000)
eventoNoCorrecta2000 <- (estado2000 == "Lenta") | (estado2000 == "Falla")
frNoCorrecta2000 <- mean(eventoNoCorrecta2000)
print(round(prop2000, 3))
print(frNoCorrecta2000)
